MODEL:
  META_ARCHITECTURE: "Baseline"

  BACKBONE:
    NAME: "build_resnet_backbone"
    NORM: "BN"
    DEPTH: "50x"
    LAST_STRIDE: 1
    FEAT_DIM: 2048
    WITH_IBN: False
    PRETRAIN: True
#    PRETRAIN_PATH: "/home/caffe/.cache/torch/checkpoints/resnet50-19c8e357.pth"
    PRETRAIN_PATH: "/home/caffe/.cache/torch/checkpoints/resnet50_caffe.pth"

  HEADS:
    NAME: "EmbeddingHead"
    NORM: "BN"
    WITH_BNNECK: True
    POOL_LAYER: "avgpool"
    NECK_FEAT: "before"
#    CLS_LAYER: "linear"
    CLS_LAYER: "arcSoftmax" # modify
    SCALE: 10
    MARGIN: 0.5

  LOSSES:
    NAME: ("CrossEntropyLoss", "TripletLoss",) # modify

    CE:
      EPSILON: 0.
      SCALE: 1. # trade-off

    TRI:
      MARGIN: 0.3
      HARD_MINING: True
      NORM_FEAT: False
      SCALE: 1. # trade-off

#    CIRCLE:
#      MARGIN: 0.25
#      ALPHA: 128
#      SCALE: 0.1

  PIXEL_MEAN: [102.9801, 115.9465, 122.7717]
  PIXEL_STD: [1., 1., 1.]

DATASETS:
  NAMES: ("PRW",)
  TESTS: ("PRW",)

INPUT:
  SIZE_TRAIN: [ 256, 128 ]
  SIZE_TEST: [ 256, 128 ]
  REA:
    ENABLED: False # modify
    PROB: 0.5
    MEAN: [ 123.675, 116.28, 103.53 ]
  DO_PAD: True

DATALOADER:
  PK_SAMPLER: True
  NAIVE_WAY: True
  NUM_INSTANCE: 4
  NUM_WORKERS: 8

SOLVER:
  OPT: "Adam"
  MAX_ITER: 120 # training epochs
  BASE_LR: 0.00035
  BIAS_LR_FACTOR: 2.
  WEIGHT_DECAY: 0.0005
  WEIGHT_DECAY_BIAS: 0.0005
  IMS_PER_BATCH: 64

  SCHED: "WarmupMultiStepLR"
  STEPS: [ 40, 90 ]
  GAMMA: 0.1

  WARMUP_FACTOR: 0.01
  WARMUP_ITERS: 10

  CHECKPOINT_PERIOD: 60

TEST:
  EVAL_PERIOD: 30
  IMS_PER_BATCH: 128

CUDNN_BENCHMARK: True
OUTPUT_DIR: "logs/prw/arcTri-s10-m0.5-woREA-BGR"
