MODEL:
  META_ARCHITECTURE: "Baseline"

  BACKBONE:
    NAME: "build_resnet_backbone"
    NORM: "BN"
    DEPTH: "101x"
    LAST_STRIDE: 1
    FEAT_DIM: 2048
    WITH_IBN: True
    WITH_NL: False
    WITH_SE: False
    PRETRAIN: True
    PRETRAIN_PATH: "/home/caffe/.cache/torch/checkpoints/resnet101-5d3b4d8f.pth"

  HEADS:
    NAME: "EmbeddingHead"
    EMBEDDING_DIM: -1
    NORM: "BN"
    WITH_BNNECK: True
    POOL_LAYER: "gempool"
    NECK_FEAT: "before"
    CLS_LAYER: "oimArcSoftmax"
    SCALE: 30
    MARGIN: 0.5

  LOSSES:
    NAME: ("CrossEntropyLoss", "TripletLoss")

    CE:
      EPSILON: 0.
      SCALE: 1.

    TRI:
      MARGIN: 0.3
      HARD_MINING: True
      NORM_FEAT: False
      SCALE: 1. # trade-off

DATASETS:
  COMBINEALL: True
  NAMES: ("DukeMTMC","SSM","MSMT17","Market1501")
  TESTS: ("Market1501",)

INPUT:
  SIZE_TRAIN: [ 384, 128 ]
  SIZE_TEST: [ 384, 128 ]
  REA:
    ENABLED: True
    PROB: 0.5
    MEAN: [ 123.675, 116.28, 103.53 ]
  DO_PAD: True

DATALOADER:
  PK_SAMPLER: True
  NAIVE_WAY: True
  NUM_INSTANCE: 4
  NUM_WORKERS: 8

SOLVER:
  OPT: "Adam"
  MAX_ITER: 70
  BASE_LR: 0.00035
  BIAS_LR_FACTOR: 2.
  WEIGHT_DECAY: 0.0005
  WEIGHT_DECAY_BIAS: 0.0005
  IMS_PER_BATCH: 64

  SCHED: "WarmupMultiStepLR"
  STEPS: [ 40, 60 ]
  GAMMA: 0.1

  WARMUP_FACTOR: 0.01
  WARMUP_ITERS: 10

  CHECKPOINT_PERIOD: 60

TEST:
  EVAL_PERIOD: 10
  IMS_PER_BATCH: 128

CUDNN_BENCHMARK: True

