MODEL:
  META_ARCHITECTURE: "CAMA"
  WEIGHTS: ""

  NUM_BRANCH: 2
  BACKBONE:
    NAME: "build_simple_resnet_backbone"
    NORM: "BN"
    DEPTH: "50x"
    LAST_STRIDE: 1
    FEAT_DIM: 2048
    WITH_IBN: False
    PRETRAIN: True
    PRETRAIN_PATH: "/home/caffe/.cache/torch/checkpoints/resnet50-19c8e357.pth"

  HEADS:
    NAME: "MultiHead"
    NORM: "BIN" # todo
    WITH_BNNECK: True
    POOL_LAYER: "avgpool"
    NECK_FEAT: "before"
    CLS_LAYER: "linear"
  #    CLS_LAYER: "arcSoftmax" # modify
  #    SCALE: 10
  #    MARGIN: 0.5

  LOSSES:
    NAME: ("CrossEntropyLoss",) # # todo TripletLoss

    CE:
      EPSILON: 0.
      SCALE: 1.0 # todo

    TRI:
      MARGIN: 0.3
      HARD_MINING: True
      NORM_FEAT: False
      SCALE: 1. # trade-off

    OAP:
      TAU: 0.1
      SCALE: 1.

DATASETS:
  NAMES: ("Market1501",)
  TESTS: ("Market1501",)

INPUT:
  SIZE_TRAIN: [ 256, 128 ]
  SIZE_TEST: [ 256, 128 ]
  REA:
    ENABLED: False # todo
    PROB: 0.5
    MEAN: [ 123.675, 116.28, 103.53 ]
  DO_PAD: True

DATALOADER:
  PK_SAMPLER: False # todo
  NAIVE_WAY: True
  NUM_INSTANCE: 4
  NUM_WORKERS: 8

SOLVER:
  OPT: "Adam"
  MAX_ITER: 70 # todo
  BASE_LR: 0.00035
  BIAS_LR_FACTOR: 2.
  WEIGHT_DECAY: 0.0005
  WEIGHT_DECAY_BIAS: 0.0005
  IMS_PER_BATCH: 64

  SCHED: "WarmupMultiStepLR"
  STEPS: [ 40, 60 ]
  GAMMA: 0.1

  WARMUP_FACTOR: 0.01
  WARMUP_ITERS: 10

  CHECKPOINT_PERIOD: 60

TEST:
  EVAL_PERIOD: 10
  IMS_PER_BATCH: 128
  METRIC: "cosine" # euclidean

CUDNN_BENCHMARK: True
OUTPUT_DIR: "logs/mk/cama"
