MODEL:
  META_ARCHITECTURE: "MGN"
  FREEZE_LAYERS: ["backbone","b1", "b2", "b3",]

  BACKBONE:
    NAME: "build_resnet_backbone"
    NORM: "BN"
    DEPTH: "50x"
    LAST_STRIDE: 1
    FEAT_DIM: 2048
    WITH_IBN: True
    WITH_NL: False
    PRETRAIN: True
    PRETRAIN_PATH: "/home/caffe/.cache/torch/checkpoints/resnet50-19c8e357.pth"

  HEADS:
    NAME: "EmbeddingHead"
    EMBEDDING_DIM: -1
    NORM: "BN"
    WITH_BNNECK: True
    POOL_LAYER: "gempoolP"
    NECK_FEAT: "after"
    #    CLS_LAYER: "oimCircleSoftmax"
    #    SCALE: 64
    #    MARGIN: 0.35
    CLS_LAYER: "oimArcSoftmax"
    SCALE: 30
    MARGIN: 0.5

  LOSSES:
    NAME: ("CrossEntropyLoss", "TripletLoss",)

    CE:
      EPSILON: 0.
      SCALE: 1.

    TRI:
      MARGIN: 0.0
      HARD_MINING: True
      NORM_FEAT: False
      SCALE: 1.

DATASETS:
  COMBINEALL: True
  NAMES: ("DukeMTMC","SSM","MSMT17",)
  TESTS: ("Market1501",) # Market1501

INPUT:
  SIZE_TRAIN: [384, 128]
  SIZE_TEST: [384, 128]
  REA:
    ENABLED: True
    PROB: 0.5
    MEAN: [123.675, 116.28, 103.53]
  DO_PAD: True
  DO_AUTOAUG: True

DATALOADER:
  PK_SAMPLER: True
  NAIVE_WAY: True
  NUM_INSTANCE: 16
  NUM_WORKERS: 8

SOLVER:
  OPT: "Adam"
  MAX_ITER: 60
  BASE_LR: 0.00035
  BIAS_LR_FACTOR: 1.
  WEIGHT_DECAY: 0.0005
  WEIGHT_DECAY_BIAS: 0.0005
  IMS_PER_BATCH: 64
  GAMMA: 0.1

  SCHED: "WarmupCosineAnnealingLR"
  DELAY_ITERS: 30
  ETA_MIN_LR: 0.00000077

  WARMUP_FACTOR: 0.01
  WARMUP_ITERS: 10
  FREEZE_ITERS: 10

  CHECKPOINT_PERIOD: 30

TEST:
  EVAL_PERIOD: 10
  IMS_PER_BATCH: 128

CUDNN_BENCHMARK: True


