MODEL:
  META_ARCHITECTURE: "OAP"
  #  FREEZE_LAYERS: ["stem", "middle", "transform", "local_transform" ]
  FREEZE_LAYERS: [ "stem", "middle", "transform", "local_transform", "local_branch", "heads" ]

  NUM_BRANCH: 2
  GLOBAL_ATTN: False
  BACKBONE:
    NAME: "build_simple_resnet_backbone"
    NORM: "BN"
    DEPTH: "50x"
    LAST_STRIDE: 1
    FEAT_DIM: 2048
    WITH_IBN: False
    WITH_CSA: False # todo
    PRETRAIN: True
    PRETRAIN_PATH: "/home/caffe/.cache/torch/checkpoints/resnet50-19c8e357.pth"

  HEADS:
    NAME: "MultiHead"
    NORM: "BN"
    WITH_BNNECK: True
    POOL_LAYER: "avgpool" # todo
    NECK_FEAT: "before"
    CLS_LAYER: "linear"

  LOSSES:
    NAME: ("CrossEntropyLoss", ) # todo TripletLoss

    CE:
      EPSILON: 0.
      SCALE: 1. # trade-off

    TRI:
      MARGIN: 0.3
      HARD_MINING: True
      NORM_FEAT: False
      SCALE: 1. # trade-off

    OAP:
      TAU: 1.
      SCALE: 10. # trade-off

DATASETS:
  NAMES: ("Market1501",)
  TESTS: ("Market1501",)

INPUT:
  SIZE_TRAIN: [ 384, 128 ]
  SIZE_TEST: [ 384, 128 ]
  REA:
    ENABLED: False # todo
    PROB: 0.5
    MEAN: [ 123.675, 116.28, 103.53 ]
  DO_PAD: True

DATALOADER:
  PK_SAMPLER: True # todo
  NAIVE_WAY: True
  NUM_INSTANCE: 16
  NUM_WORKERS: 8

SOLVER:
  OPT: "Adam"
  MAX_ITER: 60
  BASE_LR: 0.00035
  BIAS_LR_FACTOR: 1.
  WEIGHT_DECAY: 0.0005
  WEIGHT_DECAY_BIAS: 0.0005
  IMS_PER_BATCH: 64

  SCHED: "WarmupCosineAnnealingLR"
  DELAY_ITERS: 30
  ETA_MIN_LR: 0.00000077
  GAMMA: 0.1

  WARMUP_FACTOR: 0.01
  WARMUP_ITERS: 10
  FREEZE_ITERS: 10

  CHECKPOINT_PERIOD: 30

TEST:
  EVAL_PERIOD: 10
  IMS_PER_BATCH: 128
  METRIC: "euclidean" # [euclidean cosine]

CUDNN_BENCHMARK: False
