MODEL:
  META_ARCHITECTURE: "SDC"
  FREEZE_LAYERS: [ "backbone", "global_branch", ]

  NUM_BRANCH: 1
  BACKBONE:
    NAME: "build_simple_resnet_backbone"
    NORM: "BN"
    DEPTH: "50x"
    LAST_STRIDE: 1
    FEAT_DIM: 2048
    WITH_IBN: False
    WITH_CSA: False
    PRETRAIN: True
    PRETRAIN_PATH: "/home/caffe/.cache/torch/checkpoints/resnet50-19c8e357.pth"

  HEADS:
    NAME: "MultiHead"
    NORM: "BN"
    WITH_BNNECK: True # TODO
    POOL_LAYER: "avgpool"
    NECK_FEAT: "before" # [before after] TODO
    CLS_LAYER: "circleSoftmax" # [linear arcSoftmax] TODO
    SCALE: 64
    MARGIN: 0.35

  LOSSES:
    NAME: ("CrossEntropyLoss", "TripletLoss") # [CrossEntropyLoss TripletLoss] TODO

    CE:
      EPSILON: 0.
      SCALE: 1. # trade-off
    TRI:
      MARGIN: 0.3 # TODO
      HARD_MINING: True
      NORM_FEAT: False
      SCALE: 1. # trade-off
    OAP:
      TAU: 1.
      SCALE: 10. # trade-off

DATASETS:
  NAMES: ("Market1501",)
  TESTS: ("Market1501",)

INPUT:
  SIZE_TRAIN: [ 384, 128 ]
  SIZE_TEST: [ 384, 128 ]
  REA:
    ENABLED: False # TODO
    PROB: 0.5
    MEAN: [ 123.675, 116.28, 103.53 ]
  DO_PAD: True
  DO_AUTOAUG: False

DATALOADER:
  PK_SAMPLER: True # TODO
  NAIVE_WAY: True
  NUM_WORKERS: 8
  NUM_INSTANCE: 4 # 16 to 4

SOLVER:
  OPT: "Adam"
  MAX_ITER: 60
  BASE_LR: 0.00035
  BIAS_LR_FACTOR: 1.
  WEIGHT_DECAY: 0.0005
  WEIGHT_DECAY_BIAS: 0.0005
  IMS_PER_BATCH: 32 # 64 to 32

  SCHED: "WarmupCosineAnnealingLR"
  DELAY_ITERS: 30
  ETA_MIN_LR: 0.00000077
  GAMMA: 0.1

  WARMUP_FACTOR: 0.01
  WARMUP_ITERS: 10
  FREEZE_ITERS: 10

  CHECKPOINT_PERIOD: 30

TEST:
  EVAL_PERIOD: 10
  IMS_PER_BATCH: 128
  METRIC: "cosine" # [euclidean cosine]

CUDNN_BENCHMARK: True
